# Generated by Django 5.1.6 on 2025-02-06 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('department', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('biography', models.TextField(blank=True, null=True)),
                ('experience_years', models.PositiveIntegerField()),
                ('qualifications', models.TextField()),
                ('achievements', models.TextField(blank=True, null=True)),
                ('languages_spoken', models.CharField(max_length=255)),
                ('consultation_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_days', models.CharField(max_length=255)),
                ('available_time_from', models.TimeField()),
                ('available_time_to', models.TimeField()),
                ('contact_number', models.CharField(max_length=15)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Doctors',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, max_length=50)),
                ('blood_type', models.CharField(blank=True, max_length=3)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('languages_spoken', models.CharField(max_length=255)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('insurance_provider', models.CharField(blank=True, max_length=100)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('allergies', models.TextField(blank=True)),
                ('current_medication', models.TextField(blank=True)),
                ('past_medical_history', models.TextField(blank=True)),
                ('smoking_status', models.BooleanField(default=False)),
                ('alcohol_use', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('treatment_consent', models.BooleanField(default=False)),
                ('privacy_consent', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('doctor_response', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='user.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='user.patient')),
            ],
        ),
    ]
