# Generated by Django 5.1.6 on 2025-02-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ádmin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('pharmacist', 'Pharmacist')], max_length=10),
        ),
    ]
