# Generated by Django 5.1.6 on 2025-02-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_affroved',
            field=models.BooleanField(default=False),
        ),
    ]
